services:
  app:
    container_name: app
    build: ./docker
    volumes:
      - ./:/app
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    networks:
     - php-tp
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}

  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
     - php-tp

networks:
  php-tp:
    name: php-tp
